repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
    - id: tflint
      args:
        - "--config=.tflint.hcl"
    - id: terraform-fmt
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.47.0
  hooks:
    - id: terraform_tfsec
    - id: terraform_docs
